### ISSUE TITLE
Checklist for pre-release sprint

### ISSUE THREAD

**Issue by amenders** [Renascentinc/retina-app#63]
_Please only check off after the corresponding branch has been merged with develop_

- [x] Switch to Font Awesome

- [x] Ember power select

- [x] Improve form: do not create new record for every route entry

- [x] Create form component

- [x] Ember form validation

- [x] Style loading state

- [x] Ember asynchronous buttons

- [x] Loading progress bar (esp. on login)

- [ ] Fix dropdown bug

- [ ] Make search results lists use component(s) with mixin if necessary

- [ ] Back button uses Ember routes

- [ ] Fix styling issues overall sans-Bootstrap

- [ ] @JerebChase : database backdoor fixes

**Comment by Jbcampbe** [comment]
At the moment the `josiahc.performance` is being treated as `develop` then we were gonna merge that branch into develop as one PR. I went ahead and checked off what we have merged into that branch so far

**Comment by Jbcampbe** [comment]
We may make some requirements changes for exactly what we plan to have in `Release 2.1.0`. Also we will be changing our use of github issues. Progress on a sprint will be tracked through milestones instead of in ticket checklists. Closing and new tickets will be opened with the changes that need to go into the next release
